---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-cat"
      label: "Cat"
    - name: "02-tail"
      label: "Tail"
    - name: "03-find"
      label: "Find"
    - name: "04-grep"
      label: "Grep"
    - name: "05-df"
      label: "Df"
    - name: "06-ps"
      label: "Ps"
    - name: "07-free"
      label: "Free"

tabs:
  - name: ">_ root"
    url: /wetty/ssh/root
