=== Viewing the end of log files with 'tail'

Some files are large enough that it is not practical to display their
contents with `+cat+`. A common example is log files, which are often
packed full of information.

Since `+tail+` only displays the last lines of a file, it is
particularly useful for viewing recent entries in log files. By default,
tail shows the last ten lines of a file, but we can control how many 
lines are displayed by using the `-n` option. You may also see this in
examples as a dash followed directly by the number of lines, eg `-5`.

Let's take a look at the last two lines of the _audit_ log. Your output
may not exactly match the example below depending on system activity.

.Command
[source,bash,role=execute]
----
tail -n 2 /var/log/audit/audit.log
----

.Output
[source,text]
----
type=USER_END msg=audit(1754594818.300:8391): pid=10757 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=1000 exe="/usr/libexec/openssh/sshd-session" hostname=? addr=10.131.8.15 terminal=ssh res=success'UID="root" AUID="rhel" ID="rhel"
type=USER_LOGOUT msg=audit(1754594818.300:8392): pid=10757 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=1000 exe="/usr/libexec/openssh/sshd-session" hostname=? addr=10.131.8.15 terminal=ssh res=success'UID="root" AUID="rhel" ID="rhel"
----

If you wish to then see the entire file, a text viewer like `+less+` or
`+view+` will show the entire file.

Adding the `+-f+` option will follow the log file so that you can see
new entries as they occur. There are a number of useful options for `tail` you can 
find using `man tail`.

.Command
[source,bash,role=execute]
----
tail -f /var/log/messages
----

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Jun 18 11:23:05 localhost systemd[30108]: Finished Cleanup of User's Temporary Files and Directories.
Jun 18 11:23:05 localhost systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
Jun 18 11:23:05 localhost systemd[1]: Finished Cleanup of Temporary Directories.
Jun 18 11:23:05 localhost systemd[30111]: Finished Cleanup of User's Temporary Files and Directories.
Jun 18 11:23:05 localhost systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dclean.service.mount: Deactivated successfully.
----

Enter kbd:[CTRL+C] to break out of this stream.

The `logger` utility will write to this _messages_ log.

Execute the command below to add an entry to /var/log/messages. You will verify it is present directly after.

.Command
[source,bash,role=execute]
----
logger Hello World
----

This command has no expected output.

Confirm the message was recorded in `+var/log/messages+`.

.Command
[source,bash,role=execute]
----
tail /var/log/messages
----

.Output
[source,text]
----
Jun 18 11:23:05 localhost systemd[1]: Finished Automatically configure NetworkManager in cloud.
Jun 18 11:29:05 localhost systemd[1]: Starting Automatically configure NetworkManager in cloud...
Jun 18 11:29:05 localhost systemd[1]: nm-cloud-setup.service: Deactivated successfully.
Jun 18 11:29:05 localhost systemd[1]: Finished Automatically configure NetworkManager in cloud.
Jun 18 11:34:27 localhost root[30360]: Hello World
----

The message you just sent with `+logger+` is present in _messages_.
