=== Using 'df' to check disk usage

A large part of a system administrator’s job is to be able to diagnose
what is causing a system to misbehave. Disk space being full can lead to
unexpected behavior, so the `+df+` command is great to include in any
troubleshooting session.

The `+df+` command, short for "`disk free`", shows a breakdown of disk
usage. The `+-h+` option will present the sizes in a human readable
format:

.Command
[source,bash,role=execute]
----
df -h
----

.Output
[source,text]
----
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs           1.8G   84K  1.8G   1% /dev/shm
tmpfs           723M   11M  712M   2% /run
/dev/nvme0n1p4   50G  2.9G   47G   6% /
/dev/nvme0n1p3  495M  153M  342M  31% /boot
/dev/nvme0n1p2  200M  8.0K  200M   1% /boot/efi
tmpfs           362M     0  362M   0% /run/user/1000
tmpfs           362M  160K  362M   1% /run/user/1888
tmpfs           362M     0  362M   0% /run/user/0
tmpfs           362M     0  362M   0% /run/user/1001
----

The usage percentage (_Use%_) column is a great place to start. If any
filesystem is close to capacity, then it may be unable to perform
installations or other operations that require data to be written.
However, the absolute size of the partition will determine what "`close
to capacity`" means. In the case of this system, the root partition is
47 GiB. Therefore, even if it is at 80% usage, the filesystem will still
have ~9 GiB to work with. Probably something you need to address
eventually, but unless you are doing some storage-intensive operation
that is failing, likely not the cause of immediate issues.

The _boot_ partition is on the other end of the spectrum, with a size of
only 495 MiB. Therefore, if this filesystem is at 80% usage, there will
only be 99 MiB available. That may not be enough for basic operations
such as installing system updates. Therefore, it is very concerning if
you run `+df+` and discover one of the smaller filesystems is at 80%
usage.

NOTE: The _tmpfs_ entries are filesystems accessible by the machine
that are stored in RAM. This means that you don’t have to care as much
about these filesystems when troubleshooting using `+df+`. A reboot will
give you a fresh copy of these filesystems.
