=== Viewing processes

Just as files organize how data is stored on Linux, processes organize
all of the programs that are running on the system. The `+ps+` command
(short for Process Status) will display information about the processes
running in the current shell. To see all of the processes running on the
system and present them in a user-readable format, it is common to add
the `+aux+` options to `+ps+`.

.Command
[source,bash,role=execute]
----
ps aux
----

.Output
[source,text]
----
root           1  0.3  0.4 173728 17912 ?        Ss   11:08   0:08 /usr/lib/systemd/systemd --system --deserialize 30
root           2  0.0  0.0      0     0 ?        S    11:08   0:00 [kthreadd]
root           3  0.0  0.0      0     0 ?        I<   11:08   0:00 [rcu_gp]
root           4  0.0  0.0      0     0 ?        I<   11:08   0:00 [rcu_par_gp]
root           5  0.0  0.0      0     0 ?        I<   11:08   0:00 [slub_flushwq]
root           6  0.0  0.0      0     0 ?        I<   11:08   0:00 [netns]
root           8  0.0  0.0      0     0 ?        I<   11:08   0:00 [kworker/0:0H-events_highpri]
root           9  0.0  0.0      0     0 ?        I    11:08   0:01 [kworker/u4:0-events_unbound]
root          10  0.0  0.0      0     0 ?        I<   11:08   0:00 [kworker/0:1H-events_highpri]
root          11  0.0  0.0      0     0 ?        I<   11:08   0:00 [mm_percpu_wq]
<< OUTPUT ABRIDGED >>
----

NOTE: There is another lab which goes into depth about `+ps+` and
process management. For more info on using `+ps+` (including how to end
processes), check out the https://lab.redhat.com/service-admin[Service
Administration Basics lab,window=read-later]

The output of this command is often very lengthy, so this is a great
chance to apply what you just learned a few steps ago. Using the pipe
operator (`+|+`), pipe the output of `+ps aux+` into the `+grep+`
command to search for a specific process. Search for the `+sshd+`
process.:

.Command
[source,bash,role=execute]
----
ps aux | grep sshd
----

.Output
[source,text]
----
root       27619  0.0  0.2  15784  9292 ?        Ss   11:13   0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root       31514  0.0  0.0   6408  2172 pts/0    S+   11:55   0:00 grep --color=auto sshd
<< Output Abridged >>
----

Here the search finds the `+sshd+` process,
the output also shows the command running the search signified by `grep --color=auto sshd`.

`+ps+` is great for showing a snapshot of the active processes and their
resource usage, but sometimes it is more useful to have a utility that
keeps updating this information in real time. `+top+` does just that.

NOTE: The below command will continue updating until you quit `+top+`. To quit
`+top+` press `+q+`.

.Command
[source,bash,role=execute]
----
top
----

.Output
[source,text]
----
top - 11:57:25 up 49 min,  2 users,  load average: 0.00, 0.00, 0.01
Tasks: 140 total,   1 running, 139 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.5 us,  0.3 sy,  0.0 ni, 98.7 id,  0.0 wa,  0.2 hi,  0.0 si,  0.3 st
MiB Mem :   3614.2 total,    889.7 free,    954.2 used,   2070.4 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2660.0 avail Mem 

PID   USER      PR   NI   VIRT   RES   SHR   S   %CPU  %MEM  TIME+   COMMAND
29962 showroom  20   0   10.3g  66244  39004 S   0.7   1.8   0:11.48 node
29602 showroom  20   0 1358008  65540  35144 S   0.3   1.8   0:05.70 podman
30062 showroom  20   0   10.3g  67012  39040 S   0.3   1.8   0:10.93 node
    1 root      20   0  173728  17912  11016 S   0.0   0.5   0:08.70 systemd
----

In addition to the process info, `+top+` includes some status information:

* The system uptime
* Total number of user accounts
* 1 minute, 5 minute, and 15 minute load averages
* The total number of tasks and a breakdown of their status counts
* The kinds of tasks using the CPU
* A breakdown of memory and swap usage

NOTE: For more information on the `+top+` preamble, visit section 2 of
the https://man7.org/linux/man-pages/man1/top.1.html[top man page,window=read-later].
