Just as files organize how data is stored on Linux, processes organize
all of the programs that are running on the system. The `+ps+` command
(short for Process Status) will display information about the processes
running in the current shell. To see all of the processes running on the
system and present them in a user-readable format, it is common to add
the `+aux+` options to `+ps+`.

[source,bash]
----
ps aux
----

____
_NOTE:_ There is another lab which goes into depth about `+ps+` and
process management. For more info on using `+ps+` (including how to end
processes), check out the https://lab.redhat.com/service-admin[Service
Administration Basics lab]
____

The output of this command is often very lengthy, so this is a great
chance to apply what you just learned a few steps ago. Using the pipe
operator (`+|+`), pipe the output of `+ps aux+` into the `+grep+`
command to search for a specific process. Search for the `+sshd+`
process.:

[source,bash]
----
ps aux | grep sshd
----

Here the search finds the `+sshd+` process, but the second line of this
output shows that the search also finds itself.

`+ps+` is great for showing a snapshot of the active processes and their
resource usage, but sometimes it is more useful to have a utility that
keeps updating this information in real time. `+top+` does just that.

[source,bash]
----
top
----

In addition to the process info, `+top+` includes some status
information: * The system uptime * Total number of user accounts * 1
minute, 5 minute, and 15 minute load averages * The total number of
tasks and a breakdown of their status counts * The kinds of tasks using
the CPU * A breakdown of memory and swap usage

____
_NOTE:_ For more information on the `+top+` preamble, visit section 2 of
the https://man7.org/linux/man-pages/man1/top.1.html[top man page].
____

This output will continue updating until you quit `+top+`. To quit
`+top+` press `+q+`.
