=== Using 'free' to view information about the system memory usage

Processes require memory to run, so when the system is running low on
free memory it can slow down significantly. Let’s launch `+stress-ng+`
to create some memory pressure and look at ways to explore what's using RAM.

.Command
[source,bash,role=execute]
----
stress-ng --vm 2 --vm-bytes 1G --timeout 600s -q &
----

.Output
[source,text]
----
[1] 66948
----


The `+free+` command is useful for quickly getting a summary of memory usage.

.Command
[source,bash,role=execute]
----
free -h
----

The `+-h+` option outputs the information in a human-readable format.

.Output
[source,text]
----
               total        used        free      shared  buff/cache   available
Mem:           3.3Gi       1.8Gi       1.3Gi        33Mi       484Mi       1.5Gi
Swap:             0B          0B          0B
----

You can see that over half of the available RAM is currently being used.
If the available memory is very low, the fourth column of `+ps au+` can
be used for finding which processes are the culprits. To sort the output
by memory usage, add the `+--sort=-%mem+` option:

.Command
[source,bash,role=execute]
----
ps au --sort=-%mem
----

.Output
[source,text]
----
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       29223 45.7 17.2 629292 591732 pts/0   R    14:51   0:10 stress-ng --vm 2 --vm-bytes 1G --timeout 600s -q
root       29224 45.7 17.2 629292 591732 pts/0   R    14:51   0:10 stress-ng --vm 2 --vm-bytes 1G --timeout 600s -q
root       29220  0.0  0.6  39456 21296 pts/0    SL   14:51   0:00 stress-ng --vm 2 --vm-bytes 1G --timeout 600s -q
<< OUTPUT ABRIDGED >>
----

You can see the different worker processes that `stress-ng` has created
taking up memory under the _%MEM_ column. Once you've found the problem
process, you can now terminate it. One option would be to return to terminal
that it is running in and quit it. However, it is simpler in most cases
to use the `+kill+` command. The process ID shown in the `+ps+` output
is how you refer to the process when killing it. Kill the `+stress-ng+`
process from this terminal:

.Command
[source,bash,role=execute]
----
kill $(pidof stress-ng)
----

This command has no expected output.

Verify top is not running with `+ps au+` again.

.Command
[source,bash,role=execute]
----
ps au --sort=-%mem
----

Here’s what you should see in the terminal.

.Output
[source,text]
----
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       23972  0.0  0.2   7600  5120 pts/0    Ss   19:18   0:00 -bash
root      189060  0.0  0.2   6628  3804 pts/0    R+   20:15   0:00 ps au --sort=-%mem
root        1221  0.0  0.1   5024  1856 ttyS0    Ss+  19:11   0:00 /sbin/agetty -o -- \u --noreset --noclear --keep-baud 115200,57600,3
root        1219  0.0  0.1   4980  1848 tty1     Ss+  19:11   0:00 /sbin/agetty -o -- \u --noreset --noclear - linux
[1]+  Done                    stress-ng --vm 2 --vm-bytes 1G --timeout 600s -q
----

Notice `stress-ng` is no longer in the `ps` output. You also see the `Done` 
message from the job control system indicating the termination of a
background process.

If you want more exercises on this topic, more information on process
management can be found in the
https://lab.redhat.com/service-admin[Service Admin Basics lab^].
