---
virtualmachines:
  - name: "rhel"
    image: "rhel-9.5"
    memory: "2G"
    cores: 1
    image_size: "40G"
    packages:
      - at
      - bash-completion
      - bind-utils
      - git
      - podman
      - buildah
      - tmux
      - vim-enhanced
      - wget
      - mlocate
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
